const {chromium}=require('playwright');const assert=require('node:assert/strict');const {pathToFileURL}=require('node:url');const path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.CHROME_BIN?{executablePath:process.env.CHROME_BIN}:{})});try{
const page=await browser.newPage({viewport:{width:1440,height:900}});await page.route(/^https?:/,r=>r.abort());const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{errors.push(d.message());await d.dismiss()});await page.goto(pathToFileURL(path.join(__dirname,'../index.html')).href);
await page.fill('#nodeGroupName','Vehicle A');await page.locator('#nodeGroupName').press('Tab');
await page.fill('#latlngInput','7 0 41.2867 36.33\n7 5 41.2868 36.3301');
await page.selectOption('#newNodeGroupType','fixed');await page.click('#addNodeGroupBtn');assert.equal(await page.locator('#scenarioMobile').isDisabled(),true);
await page.fill('#nodeGroupName','Anchors');await page.locator('#nodeGroupName').press('Tab');await page.fill('#latlngInput','1 0 41.287 36.3304');
await page.selectOption('#newNodeGroupType','mobile');await page.click('#addNodeGroupBtn');await page.fill('#latlngInput','2 0 41.2871 36.3305\n2 10 41.2872 36.3306');await page.click('#convertBtn');
assert.equal(await page.locator('.node-group-item').count(),3);assert.equal(await page.locator('#output').getAttribute('data-kind'),'export');
const data=await page.evaluate(()=>({static:staticCoojaPositions,mobile:mobileCoojaTrace,groups:nodeGroups}));assert.equal(data.static.length,1);assert.ok(Math.abs(data.static[0].x)>1);assert.equal(data.mobile.trim().split('\n').length,4);assert.deepEqual(data.mobile.trim().split('\n').map(r=>Number(r.split(' ')[1])),[0,0,5,10]);assert.equal(data.groups[0].points.length,2);
// Mock directory handles to check the actual all-group Save action.
const csc=`<simconf><simulation><randomseed>1</randomseed><radiomedium>org.contikios.cooja.radiomediums.UDGM</radiomedium><motetype>${[2,1,7].map(id=>`<mote><interface_config>org.contikios.cooja.interfaces.Position<pos x="0" y="0"/></interface_config><interface_config>org.contikios.cooja.mspmote.interfaces.MspMoteID<id>${id}</id></interface_config></mote>`).join('')}</motetype></simulation></simconf>`;
await page.evaluate(csc=>{window.savedCsc=csc;window.savedRoute='';const h={getFile:async()=>new File([window.savedCsc],'groups.csc'),isSameEntry:async x=>x===h,createWritable:async()=>({write:async t=>window.savedCsc=t,close:async()=>{},abort:async()=>{}})};const r={getFile:async()=>new File([window.savedRoute],'positions.dat'),createWritable:async()=>({write:async t=>window.savedRoute=t,close:async()=>{},abort:async()=>{}})};window.showOpenFilePicker=async()=>[h];window.showDirectoryPicker=async()=>({getFileHandle:async n=>n==='groups.csc'?h:r});},csc);
await page.click('#saveBtn');await page.waitForFunction(()=>window.savedRoute.length>0);const saved=await page.evaluate(()=>({csc:window.savedCsc,route:window.savedRoute}));assert.ok(saved.csc.includes('[CONFIG_DIR]/positions.dat'));assert.deepEqual(new Set(saved.route.trim().split('\n').map(r=>r.split(' ')[0])),new Set(['0','2']));
const x=await page.evaluate(()=>{const d=new DOMParser().parseFromString(window.savedCsc,'application/xml');return d.querySelectorAll('mote')[1].querySelector('pos').getAttribute('x')});assert.notEqual(Number(x),0);
await page.evaluate(()=>persistSessionStateNow());await page.reload();assert.equal(await page.locator('.node-group-item').count(),3);await page.locator('.node-group-item').first().click();assert.ok((await page.inputValue('#latlngInput')).startsWith('7 0'));
// Polygon generation stays in the active group and does not replace other groups.
await page.evaluate(()=>{updateWorkMode('polygon');polygonDraft=[L.latLng(41.2867,36.33),L.latLng(41.2867,36.332),L.latLng(41.288,36.332),L.latLng(41.288,36.33)];deployMobileScanPathInPolygon();});assert.ok(await page.evaluate(()=>positions.length>1));
await page.locator('.node-group-item').nth(1).click();assert.equal(await page.evaluate(()=>positions.length),1);
await page.evaluate(()=>{polygonDraft=[L.latLng(41.2867,36.33),L.latLng(41.2867,36.332),L.latLng(41.288,36.332),L.latLng(41.288,36.33)];deployNodesInPolygon();});assert.ok(await page.evaluate(()=>positions.length>1));
await page.click('#deleteNodeGroupBtn');assert.equal(await page.locator('.node-group-item').count(),2);await page.click('#undoBtn');assert.equal(await page.locator('.node-group-item').count(),3);assert.equal(await page.evaluate(()=>scenario),'fixed');assert.equal(await page.locator('#scenarioFixed').getAttribute('class'),'toggle-button active');
assert.deepEqual(errors,[]);await page.screenshot({path:'/tmp/node-groups.png'});console.log('PASS: groups, names, type lock, shared origin, two-route merge, combined CSC save, persistence, polygons, undo');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
